import { InputData } from './types';
import { toSlug } from './utils';

const inputData: InputData = {
  posts: [
    {
      title: '웹디자인개발기능사 레이아웃 유형 A-1',
      slug: toSlug('webdesign layout A-1'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign01',
      images: ['/images/webdesign01.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 A-2',
      slug: toSlug('webdesign layout A-2'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign02',
      images: ['/images/webdesign02.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 A-3',
      slug: toSlug('webdesign layout A-3'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign03',
      images: ['/images/webdesign03.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 A-4',
      slug: toSlug('webdesign layout A-4'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign04',
      images: ['/images/webdesign04.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 B-1',
      slug: toSlug('webdesign layout B-1'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign05',
      images: ['/images/webdesign05.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 B-2',
      slug: toSlug('webdesign layout B-2'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign06',
      images: ['/images/webdesign06.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 B-3',
      slug: toSlug('webdesign layout B-3'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign07',
      images: ['/images/webdesign07.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 B-4',
      slug: toSlug('webdesign layout B-4'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign08',
      images: ['/images/webdesign08.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 C-1',
      slug: toSlug('webdesign layout C-1'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign09',
      images: ['/images/webdesign09.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 C-2',
      slug: toSlug('webdesign layout C-2'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign10',
      images: ['/images/webdesign10.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 C-3',
      slug: toSlug('webdesign layout C-3'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign11',
      images: ['/images/webdesign11.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형 C-4',
      slug: toSlug('webdesign layout C-4'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign/webdesign12',
      images: ['/images/webdesign12.jpg'],
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },

    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:변수',
      slug: toSlug('react javascript class1'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript/javascript01',
      images: ['/images/javascript01.jpg'],
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:배열',
      slug: toSlug('react javascript class2'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript/javascript02',
      images: ['/images/javascript02.jpg'],
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:객체',
      slug: toSlug('react javascript class3'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript/javascript03',
      images: ['/images/javascript03.jpg'],
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:객체',
      slug: toSlug('react javascript class4'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript/javascript04',
      images: ['/images/javascript04.jpg'],
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
  ],
};

export default inputData;
